baseURL: http://ddavo.me/
languageCode: en-uk
title: David Davó
theme: toha

# Manage languages
# https://gohugo.io/content-management/multilingual/
languages:
  en:
    languageName: English
    weight: 1
  es:
    languageName: Español
    weight: 1
  jp:
    languageName: 日本語
    weight: 2
# At least HTML and JSON are required for the main HTML content and
# client-side JavaScript search
outputs:
  home:
  - HTML
  - RSS
  - JSON

# Site parameters
params:
  # GitHub repo URL and branch of your site
  gitRepo: https://github.com/daviddavo/daviddavo.github.io
  gitBranch: main

  background: /images/landing/Calle_de_Alcala_Madrid_04.jpg
  logo:
    favicon: /images/logos/favicon-512x512.png

  newsletter:
    enable: false

  features:
    portfolio:
      enable: true
    analytics:
      enabled: true
      matomo:
        instance: matomo.ddavo.me
        siteId: 1
    # support:
    #   enabled: true
    #   kofi:
    #     user: ddavo
    #     text: Invite me to a coffee
    #     textColor: '#f9fafc'
    #     backgroundColor: '#248aaa'

  footer:
    enable: true
