name: Deploy site via Fleek
on: push
jobs:
  deploy-to-fleek:
    runs-on: ubuntu-latest
    env:
      FLEEK_TOKEN: ${{ secrets.FLEEK_TOKEN }}
      FLEEK_PROJECT_ID: ${{ secrets.FLEEK_PROJECT_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.130.0'
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Fleek CLI
        run: npm i -g @fleek-platform/cli

      - name: Modify hugo config
        run: |
          echo "relativeURLs: true" >> config.yaml

      - name: Build Hugo
        run: hugo --minify
      
      - name: Build & deploy sites
        run: fleek sites deploy
