name: deploy on ipfs
on:
    workflow_dispatch:
    push:
        branches:
            - main

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.130.0'
          extended: true

      - name: Build
        run: hugo -b "/"

      - name: Deploy to Kubo
        uses: ipshipyard/ipfs-deploy-action@v1
        id: shipyard
        with:
          path-to-deploy: './public'
          kubo-api-url: ${{ secrets.KUBO_API_URL }} 
          kubo-api-auth: ${{ secrets.KUBO_AUTH }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update IPNS Pointer for Blog
        run: |
          K_USER=$(echo "${{ secrets.KUBO_AUTH }}" | cut -d':' -f2)
          K_PASS=$(echo "${{ secrets.KUBO_AUTH }}" | cut -d':' -f3)
          curl -X POST -u "$K_USER:$K_PASS" \
          "${{ secrets.KUBO_API_URL_HTTP }}/api/v0/name/publish?resolve=true&arg=${{ steps.shipyard.outputs.cid }}&key=ddavo-me"